spring:
  application:
    name: csa-api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://csa-auth-service
          predicates:
            - Path=/auth/api/v1/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
