spring:
  application:
    name: ppt-api-gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://ppt-auth-service
          predicates:
            - Path=/auth/api/v1/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://ppt-user-service
          predicates:
            - Path=/user/api/v1/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: business-unit-service
          uri: lb://ppt-business-unit-service
          predicates:
            - Path=/business-unit/api/v1/**
          filters:
            - RewritePath=/business-unit/(?<path>.*), /$\{path}

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

