spring:
  application:
    name: ppt-business-unit-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
      database: ppt_auth
  jackson:
    date-format: "YYYY-MM-dd"
    time-zone: Europe/Paris
    locale: fr_FR
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

jwt:
  # SH1-256 secret-key: jeanvaljean with c@ramel hash text
  # from this site https://www.devglan.com/online-tools/hmac-sha256-online
  # secret-key: 1a0a6b99a89af68d186f8aff153e4d3257170fd2b37f81f9786b80748b116a13
  # SHA-512 secret-key: jeanvaljean with c@ramel hash text
  # from this site https://www.devglan.com/online-tools/hmac-sha256-online
  secret-key: 338c8f3c59577f84fbafa14a6bfb13e08bb0a40525c5fd0ed4964b5acc4a671aced78bb498c2eb947f8ca57d9089b1cab7651544e48451db925f7eb7afd5bd0b
  expiration-time: 600   # 10 minutes
  auth-header: Authorization

server:
  port: 26003

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: DEBUG
