spring:
  application:
    name: ppt-auth-service
  data:
    mongodb:
      host: ${MONGO_SERVER_IP:127.0.0.1}
      port: ${MONGO_SERVER_PORT:27017}
      database: ppt_auth
      auto-index-creation: true
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
    default-property-inclusion: NON_NULL

jwt:
  # secret-key: jeanvaljean with c@ramel hash text
  # from this site https://www.devglan.com/online-tools/hmac-sha256-online
  secret-key: 1a0a6b99a89af68d186f8aff153e4d3257170fd2b37f81f9786b80748b116a13
  expiration-time: 600   # 10 minutes
  auth-header: Authorization

server:
  port: 26001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: DEBUG